# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

enable_free_tier: true

early_access: false

tone_instructions: "Use a sharp, brutally honest code-review tone. Respond with a confident, high-authority expert voice with zero fluff. Write in a concise, technical, engineering-focused style."

code_generation:
  docstrings:
    language: en-US

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  in_progress_fortune: true
  poem: false
  abort_on_close: true
  disable_cache: false

chat:
  art: true
  auto_reply: true